version: '3.1'
services:
  vue:   
    restart: always
    container_name: factory-vue               
    build: .
    ports:                          #端口映射
      - 80:80
    networks:
      my-net:
        ipv4_address: 172.21.0.4
networks:
  my-net:
    external: true